[build]
  publish = "public"  # The folder to publish (if you have static files)
  command = "npm run build"  # Command to run before deployment

[[redirects]]
  from = "/*"
  to = "/home.ejs"
  status = 200
